include:
  - board: nice_nano_v2
    shield: splitkb_aurora_corne_left nice_view_adapter nice_view_battery
    snippet: studio-rpc-usb-uart
    artifact-name: splitkb_aurora_corne_left
  - board: nice_nano_v2
    shield: splitkb_aurora_corne_right nice_view_adapter nice_view_battery
    snippet: studio-rpc-usb-uart
    artifact-name: splitkb_aurora_corne_right
  - board: nice_nano_v2
    shield: settings_reset
